spring.application.name=corporate-credit-management

spring.datasource.url=jdbc:postgresql://localhost:5432/corporate_credit_management
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
